# Generated by Django 3.2 on 2021-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.TextField(max_length=400, null=True)),
                ('Lastname', models.TextField(max_length=400, null=True)),
                ('Email', models.CharField(max_length=400, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
