# Generated by Django 3.2 on 2021-04-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='City',
            field=models.CharField(choices=[('Kampala', 'Kampala'), ('Wakiso', 'Wakiso')], default='Kampala', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='Program',
            field=models.CharField(choices=[('Artificialintelligence', 'Artificialintelligence'), ('cybersecurity', 'cybersecurity'), ('Webdevelopment', 'Webdevelopment'), ('Networks and system administration', 'Networks and system administration')], max_length=400, null=True),
        ),
    ]
