# Generated by Django 3.2 on 2021-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0003_auto_20210430_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='Program',
        ),
        migrations.AddField(
            model_name='registrationform',
            name='program',
            field=models.CharField(default='cybersecurity', max_length=400),
            preserve_default=False,
        ),
    ]
