# Generated by Django 3.1.7 on 2021-05-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0004_auto_20210430_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newslettersubcriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cityy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='City',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Email',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Firstname',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Lastname',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Phone',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='program',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
