# Generated by Django 3.1.7 on 2021-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0005_auto_20210502_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='program',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
