# Generated by Django 3.1.7 on 2021-05-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0006_auto_20210502_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='City',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='program',
        ),
    ]
