# Generated by Django 3.1.7 on 2021-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0007_auto_20210502_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='Address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='City',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='program',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
